version: '2'
services:
  db:
    container_name: dog_db
    image: postgres:16.4-alpine
    hostname: postgreshost
    restart: always
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dogs
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/seed-data:/etc/seed-data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d dogs']
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: dog_app
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: sh -c "npm run start:dev"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/app/src
        - action: rebuild
          path: package.json
    ports:
      - '3000:3000'

  pgadmin:
    container_name: dog_pgadmin
    depends_on:
      db:
        condition: service_healthy
    image: dpage/pgadmin4
    restart: always
    ports:
      - '3001:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    user: root
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
