version: '2'
services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    command: npm run start:prod
    volumes:
      - .:/user/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
