version: '2'
services:
  db:
    container_name: dog_db
    image: postgres:16.4-alpine
    hostname: postgreshost
    restart: always
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dogs
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d dogs']
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: dog_app
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: sh -c "npm run build && npm run start:prod"
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
