services:
  db:
    container_name: dog_db
    image: postgres:16.4-alpine
    hostname: postgreshost
    restart: always
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dogs
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/seed-data:/etc/seed-data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d dogs']
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: dog_app
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: sh -c "npm run build && npm run start:prod"
    ports:
      - '3000:3000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  test:
    container_name: dog_app_test
    depends_on:
      app:
        condition: service_healthy
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    command: sh -c "npm run test:e2e"
